
name: Run Calculator

on:
  push:
    branches: [ main] 
  pull_request: 
      branches: [ main]
jobs:
  run-calc:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Setup Node.js 
        uses: actions/setup-node@v4 
        with:
          node-version: '18'
      - name: Run calculator
        run: npm start